# Generated by Django 5.2.17 on 2026-09-02 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
        ('delivery', '0006_deliveryjob_created_by_repositoryconfig_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('System default', 'System default'), ('Light', 'Light'), ('Dark', 'Dark')], default='System default', max_length=30)),
                ('font', models.CharField(choices=[('Inter', 'Inter'), ('Noto Sans', 'Noto Sans'), ('Poppins', 'Poppins')], default='Inter', max_length=30)),
                ('language', models.CharField(choices=[('English', 'English'), ('Telugu', 'Telugu'), ('Hindi', 'Hindi')], default='English', max_length=30)),
                ('default_delivery_mode', models.CharField(choices=[('Live', 'Live'), ('Dry run', 'Dry run'), ('Preview', 'Preview')], default='Live', max_length=30)),
                ('items_per_page', models.PositiveIntegerField(default=10)),
                ('confirm_before_delivery', models.BooleanField(default=True)),
                ('auto_refresh_dashboard', models.BooleanField(default=True)),
                ('auto_refresh_interval', models.PositiveIntegerField(default=5, help_text='Dashboard auto-refresh interval in minutes.')),
                ('successful_deliveries', models.BooleanField(default=True)),
                ('failed_deliveries', models.BooleanField(default=True)),
                ('dry_run_completions', models.BooleanField(default=True)),
                ('repository_connection_failures', models.BooleanField(default=True)),
                ('notification_recipients', models.JSONField(blank=True, default=list, help_text='Email addresses that receive application notification messages.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='delivery.repositoryconfig')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
