# Generated by Django 5.2.17 on 2026-08-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryjob',
            name='archive_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='is_dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='job_reference',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='repositoryconfig',
            name='connection_status',
            field=models.CharField(default='UNKNOWN', max_length=30),
        ),
        migrations.AddField(
            model_name='repositoryconfig',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repositoryconfig',
            name='last_connection_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repositoryconfig',
            name='repository_type',
            field=models.CharField(choices=[('LOCAL', 'Local Git'), ('GITHUB', 'GitHub'), ('GITLAB', 'GitLab'), ('AZURE_DEVOPS', 'Azure DevOps'), ('INTERNAL_GIT', 'Internal Git')], default='LOCAL', max_length=30),
        ),
        migrations.AddField(
            model_name='repositoryconfig',
            name='repository_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='repositoryconfig',
            name='email_mode',
            field=models.CharField(choices=[('SIMULATION', 'Simulation'), ('SMTP', 'SMTP')], default='SIMULATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='repositoryconfig',
            name='local_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='repositoryconfig',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
