# Generated by Django 5.2.17 on 2026-08-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryjob_archive_path_deliveryjob_is_dry_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryconfig',
            name='target_path',
            field=models.CharField(default='logs', help_text='File or directory to collect from the repository.', max_length=500),
        ),
    ]
