# Generated by Django 5.2.17 on 2026-08-12 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_repositoryconfig_target_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryconfig',
            name='target_path',
            field=models.CharField(default='logs', max_length=500),
        ),
        migrations.CreateModel(
            name='RepositoryCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('NONE', 'Public / No Authentication'), ('PAT', 'Personal Access Token'), ('SSH', 'SSH Key')], default='NONE', max_length=20)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('encrypted_token', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='delivery.repositoryconfig')),
            ],
        ),
    ]
