# Generated by Django 5.2.17 on 2026-08-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_repositoryconfig_target_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryconfig',
            name='targets',
            field=models.JSONField(blank=True, default=list, help_text='List of files or directories to collect. Each target should contain a path and optional allowed extensions.'),
        ),
        migrations.AlterField(
            model_name='repositoryconfig',
            name='email_mode',
            field=models.CharField(choices=[('SIMULATION', 'Simulation'), ('SMTP', 'Smtp')], default='SIMULATION', max_length=30),
        ),
    ]
