# Generated by Django 5.2.17 on 2026-08-20 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_repositoryconfig_targets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryjob',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who started this delivery job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repositoryconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this repository configuration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_user_time_idx'), models.Index(fields=['action', '-timestamp'], name='audit_action_time_idx'), models.Index(fields=['resource', '-timestamp'], name='audit_resource_time_idx')],
            },
        ),
    ]
